import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

test('mcp-server registers agentify_* tools only', async () => {
  const src = await fs.readFile(path.join(__dirname, '..', 'mcp-server.mjs'), 'utf8');

  assert.ok(src.includes("'agentify_query'"), 'expected agentify_query tool');
  assert.ok(src.includes('expectedModel'), 'expected query model-selection forwarding');
  assert.ok(src.includes('conversationUrl: data.result?.conversationUrl || null'), 'expected terminal conversation URL forwarding');
  assert.ok(src.includes('modelEvidence: data.result?.modelEvidence || null'), 'expected terminal model evidence forwarding');
  assert.ok(src.includes("status: data.result?.status || 'COMPLETE'"), 'expected structured query terminal status');
  assert.ok(src.includes('promptPath: z.string().optional()'), 'expected exact prompt-file input');
  assert.ok(src.includes("await fs.readFile(resolvedPromptPath, 'utf8')"), 'expected Agentify to read prompt files directly');
  assert.ok(src.includes('exactly_one_of_prompt_or_promptPath_required'), 'expected ambiguous prompt input rejection');
  assert.ok(src.includes("'agentify_wait_response'"), 'expected wait-response tool');
  assert.ok(src.includes("'agentify_list_conversations'"), 'expected conversation-list tool');
  assert.ok(src.includes("'agentify_open_conversation'"), 'expected conversation-open tool');
  assert.ok(src.includes("'agentify_new_conversation'"), 'expected new-conversation tool');
  assert.ok(src.includes("path: '/wait-response'"), 'expected wait-response endpoint forwarding');
  assert.ok(src.includes("'agentify_review_query'"), 'expected strict agentify_review_query tool');
  assert.ok(src.includes("path: '/review-query'"), 'expected strict review-query endpoint forwarding');
  assert.ok(src.includes("'agentify_review_preflight'"), 'expected native non-sending strict preflight tool');
  assert.ok(src.includes("path: '/review-preflight'"), 'expected native review-preflight endpoint forwarding');
  assert.ok(src.includes("'agentify_review_reasoning_mode_preflight'"), 'expected native no-send ChatGPT reasoning-mode preflight tool');
  assert.ok(src.includes("path: '/review-reasoning-mode-preflight'"), 'expected native reasoning-mode endpoint forwarding');
  assert.ok(src.includes("'agentify_review_reasoning_mode_diagnostics'"), 'expected native read-only ChatGPT reasoning-mode diagnostic tool');
  assert.ok(src.includes("path: '/review-reasoning-mode-diagnostics'"), 'expected native reasoning-mode diagnostic endpoint forwarding');
  assert.ok(src.includes("'agentify_review_chatgpt_profile_snapshot'"), 'expected native aggregate-only ChatGPT profile snapshot tool');
  assert.ok(src.includes("path: '/review-chatgpt-profile-snapshot'"), 'expected native profile snapshot endpoint forwarding');
  assert.ok(src.includes("'agentify_operator_observe'"), 'expected closed-loop native operator observation tool');
  assert.ok(src.includes("'agentify_operator_act'"), 'expected closed-loop native operator action tool');
  assert.ok(src.includes("'agentify_operator_wait'"), 'expected latency-aware native operator wait tool');
  assert.ok(src.includes("path: '/operator-observe'"), 'expected operator observation endpoint forwarding');
  assert.ok(src.includes("path: '/operator-act'"), 'expected operator action endpoint forwarding');
  assert.ok(src.includes("path: '/operator-wait'"), 'expected operator wait endpoint forwarding');
  assert.equal(src.includes("'agentify_review_prompt_sha256_preflight'"), false, 'caller SHA preflight must stay absent');
  assert.equal(src.includes("'agentify_review_cancel_prepared'"), false, 'redundant zero-send retirement tool must stay absent');
  assert.ok(src.includes("'agentify_review_observe'"), 'expected native ledger-only strict observation tool');
  assert.ok(src.includes("path: '/review-observe'"), 'expected native review-observe endpoint forwarding');
  for (const field of ['stableKey', 'provider', 'model', 'conversationUrl', 'conversationId', 'idempotencyKey', 'promptSha256', 'responsePath', 'verifyExisting', 'firstBinding', 'existingTabId']) {
    assert.ok(src.includes(`${field}:`), `expected ${field} review field`);
  }
  assert.ok(src.includes('promptSha256: z.string().optional()'), 'expected caller prompt hash to be optional and tool-local');
  assert.ok(src.includes('responsePath: z.string()'), 'expected an explicit full-response archive path');
  assert.ok(src.includes("z.enum(['chatgpt', 'gemini'])"), 'expected strict Gemini provider support');
  assert.ok(src.includes("'agentify_download_images'"), 'expected agentify_download_images tool');
  assert.ok(src.includes("'agentify_list_watch_folders'"), 'expected agentify_list_watch_folders tool');
  assert.ok(src.includes("'agentify_add_watch_folder'"), 'expected agentify_add_watch_folder tool');
  assert.ok(src.includes("'agentify_remove_watch_folder'"), 'expected agentify_remove_watch_folder tool');
  assert.ok(src.includes("'agentify_open_watch_folder'"), 'expected agentify_open_watch_folder tool');
  assert.ok(src.includes("'agentify_save_bundle'"), 'expected agentify_save_bundle tool');
  assert.ok(src.includes("'agentify_list_bundles'"), 'expected agentify_list_bundles tool');
  assert.ok(src.includes("'agentify_save_artifacts'"), 'expected agentify_save_artifacts tool');
  assert.ok(src.includes("'agentify_list_artifacts'"), 'expected agentify_list_artifacts tool');
  assert.ok(src.includes('model,'), 'expected model hint to be forwarded to HTTP query');
  assert.ok(src.includes("body: { model, key, name, show: typeof show === 'boolean' ? show : undefined }"), 'expected model hint on tab_create');
  assert.ok(src.includes("body: { model, tabId, key, maxChars: maxChars || 200_000 }"), 'expected model hint on read_page');
  assert.ok(src.includes("body: { model, tabId, key, timeoutMs: timeoutMs || 10 * 60_000 }"), 'expected model hint on ensure_ready');
  assert.ok(src.includes("body: { model, tabId, key, mode: mode || 'all', maxImages: maxImages || 6, maxFiles: maxFiles || 6 }"), 'expected model hint on save_artifacts');
  assert.ok(src.includes("if (key) qs.set('key', key);"), 'expected status key selector forwarding');
  assert.ok(src.includes("if (vendorId) qs.set('vendorId', vendorId);"), 'expected status vendorId selector forwarding');
  assert.ok(src.includes("if (model) qs.set('model', model);"), 'expected status model selector forwarding');
  assert.ok(src.includes('resolveLocalPaths(attachments || [])'), 'expected attachments to be normalized relative to MCP cwd');
  assert.ok(src.includes('resolveLocalPaths(contextPaths || [])'), 'expected contextPaths to be normalized relative to MCP cwd');
  assert.ok(src.includes("source: 'mcp'"), 'expected MCP calls to mark runtime source');
  assert.ok(src.includes('folderPath: z.string()'), 'expected add_watch_folder to use folderPath field name');
  assert.ok(src.includes("throw new Error('missing_watch_folder_path')"), 'expected blank watch-folder path guard');
  assert.ok(src.includes('maxContextChunkChars: z.number().optional()'), 'expected maxContextChunkChars input');
  assert.ok(src.includes('maxContextChunksPerFile: z.number().optional()'), 'expected maxContextChunksPerFile input');
  assert.ok(src.includes('maxContextInlineFiles: z.number().optional()'), 'expected maxContextInlineFiles input');
  assert.ok(!src.includes('void model;'), 'model hint should not be dropped');

  assert.ok(!src.includes('browser_'), 'should not contain browser_* tools/aliases');
  assert.ok(!src.includes('registerToolWithAliases'), 'should not contain alias helper');
});
